name: Build_Jesee_Store
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Webview to APK
        uses: swayangjit/webview-to-app-action@v1.1
        with:
          app-name: "Jesee Store"
          url: "https://jesee.store/"
